/**
 * Complete Nanakshahi Calendar 557 (2025-2026) - Official SGPC Calendar
 * Source: https://www.sikhnet.com/pages/sikh-gurpurab-calendar
 * Includes: Sangrand, Masia, Puranmasi, Gurpurabs, Shaheedi, Historical events
 * ALL dates in chronological order
 */

export interface SikhEvent {
  id: string;
  name: string;
  nameGurmukhi: string;
  nanakshahiDate: string;
  gregorianDate: string;
  type: 'sangrand' | 'masia' | 'puranmasi' | 'gurpurab' | 'martyrdom' | 'historical' | 'festival' | 'gurgaddi' | 'jotijot' | 'birth';
  description: string;
  year?: string;
}

/**
 * Get complete Nanakshahi calendar 557 (2025-2026) in date order
 */
export function getCompleteNanakshahiCalendar(): SikhEvent[] {
  return [
    // ===== JANUARY 2026 =====
    {
      id: 'jan-14-sangrand',
      name: 'Sangrand - Maagh Month Begins',
      nameGurmukhi: 'ਸੰਗਰਾਂਦ - ਮਾਘ',
      nanakshahiDate: '1 Maagh',
      gregorianDate: 'January 14, 2026',
      type: 'sangrand',
      description: 'First day of Maagh month in Nanakshahi calendar',
    },
    {
      id: 'jan-14-foundation',
      name: 'Foundation of Harmandir Sahib',
      nameGurmukhi: 'ਹਰਿਮੰਦਰ ਸਾਹਿਬ ਦੀ ਨੀਂਹ',
      nanakshahiDate: '1 Maagh',
      gregorianDate: 'January 14, 2026',
      type: 'historical',
      description: 'Foundation stone laid for Sachkhand Sri Harmandir Sahib (Golden Temple), Amritsar',
      year: '1588 CE',
    },
    {
      id: 'jan-14-maghi',
      name: 'Maghi Mela - Muktsar Sahib',
      nameGurmukhi: 'ਮਾਘੀ ਮੇਲਾ',
      nanakshahiDate: '1 Maagh',
      gregorianDate: 'January 14, 2026',
      type: 'festival',
      description: 'Commemorates Battle of Muktsar and sacrifice of 40 Muktas (Chali Mukte)',
      year: '1705 CE',
    },
    {
      id: 'jan-14-masia',
      name: 'Masia (New Moon)',
      nameGurmukhi: 'ਮੱਸਿਆ',
      nanakshahiDate: '1 Maagh',
      gregorianDate: 'January 14, 2026',
      type: 'masia',
      description: 'New moon day - beginning of lunar cycle',
    },
    {
      id: 'jan-18-puranmasi',
      name: 'Puranmasi (Full Moon)',
      nameGurmukhi: 'ਪੂਰਨਮਾਸੀ',
      nanakshahiDate: '5 Maagh',
      gregorianDate: 'January 18, 2026',
      type: 'puranmasi',
      description: 'Full moon day',
    },
    {
      id: 'jan-23-marriage',
      name: 'Marriage of Guru Gobind Singh Ji',
      nameGurmukhi: 'ਗੁਰੂ ਗੋਬਿੰਦ ਸਿੰਘ ਜੀ ਦਾ ਵਿਆਹ',
      nanakshahiDate: '10 Maagh',
      gregorianDate: 'January 23, 2026',
      type: 'historical',
      description: 'Marriage with Mata Jito Ji at Guru Ka Lahore (Anandpur Sahib)',
      year: '1677 CE',
    },
    {
      id: 'jan-27-deep-singh-birth',
      name: 'Birthday - Baba Deep Singh Ji',
      nameGurmukhi: 'ਬਾਬਾ ਦੀਪ ਸਿੰਘ ਜੀ ਦਾ ਜਨਮ',
      nanakshahiDate: '14 Maagh',
      gregorianDate: 'January 27, 2026',
      type: 'birth',
      description: 'Birth of legendary Sikh warrior and scholar Baba Deep Singh Ji',
      year: '1682 CE',
    },
    {
      id: 'jan-31-guru7-parkash',
      name: 'Parkash Purab - Guru Har Rai Ji',
      nameGurmukhi: 'ਗੁਰੂ ਹਰ ਰਾਇ ਜੀ ਦਾ ਪ੍ਰਕਾਸ਼ ਪੁਰਬ',
      nanakshahiDate: '18 Maagh',
      gregorianDate: 'January 31, 2026',
      type: 'gurpurab',
      description: 'Birth of seventh Sikh Guru',
      year: '1630 CE',
    },

    // ===== FEBRUARY 2026 =====
    {
      id: 'feb-01-puranmasi',
      name: 'Puranmasi (Full Moon)',
      nameGurmukhi: 'ਪੂਰਨਮਾਸੀ',
      nanakshahiDate: '19 Maagh',
      gregorianDate: 'February 1, 2026',
      type: 'puranmasi',
      description: 'Full moon day',
    },
    {
      id: 'feb-01-bhagat-ravidas',
      name: 'Birth - Bhagat Ravidas Ji',
      nameGurmukhi: 'ਭਗਤ ਰਵਿਦਾਸ ਜੀ ਦਾ ਜਨਮ',
      nanakshahiDate: '19 Maagh',
      gregorianDate: 'February 1, 2026',
      type: 'birth',
      description: 'Birth of Sant Ravidas Ji, whose hymns are in Guru Granth Sahib',
      year: '1377 CE',
    },
    {
      id: 'feb-09-vadda-ghallughara',
      name: 'Vadda Ghallughara (Great Holocaust)',
      nameGurmukhi: 'ਵੱਡਾ ਘੱਲੂਘਾਰਾ',
      nanakshahiDate: '27 Maagh',
      gregorianDate: 'February 9, 2026',
      type: 'martyrdom',
      description: 'Massacre at Kup Rohira (Sangrur) - thousands of Sikhs martyred',
      year: '1762 CE',
    },
    {
      id: 'feb-11-ajit-singh-birth',
      name: 'Birthday - Sahibzada Baba Ajit Singh Ji',
      nameGurmukhi: 'ਸਾਹਿਬਜ਼ਾਦਾ ਬਾਬਾ ਅਜੀਤ ਸਿੰਘ ਜੀ ਦਾ ਜਨਮ',
      nanakshahiDate: '29 Maagh',
      gregorianDate: 'February 11, 2026',
      type: 'birth',
      description: 'Birth of eldest son of Guru Gobind Singh Ji',
      year: '1687 CE',
    },
    {
      id: 'feb-12-sangrand',
      name: 'Sangrand - Phagan Month Begins',
      nameGurmukhi: 'ਸੰਗਰਾਂਦ - ਫੱਗਣ',
      nanakshahiDate: '1 Phagan',
      gregorianDate: 'February 12, 2026',
      type: 'sangrand',
      description: 'First day of Phagan month',
    },
    {
      id: 'feb-12-masia',
      name: 'Masia (New Moon)',
      nameGurmukhi: 'ਮੱਸਿਆ',
      nanakshahiDate: '1 Phagan',
      gregorianDate: 'February 12, 2026',
      type: 'masia',
      description: 'New moon day',
    },
    {
      id: 'feb-17-puranmasi',
      name: 'Puranmasi (Full Moon)',
      nameGurmukhi: 'ਪੂਰਨਮਾਸੀ',
      nanakshahiDate: '6 Phagan',
      gregorianDate: 'February 17, 2026',
      type: 'puranmasi',
      description: 'Full moon day',
    },

    // ===== MARCH 2026 =====
    {
      id: 'mar-03-puranmasi',
      name: 'Puranmasi (Full Moon)',
      nameGurmukhi: 'ਪੂਰਨਮਾਸੀ',
      nanakshahiDate: '18 Phagan',
      gregorianDate: 'March 3, 2026',
      type: 'puranmasi',
      description: 'Full moon day',
    },
    {
      id: 'mar-04-hola-mohalla-old',
      name: 'Hola Mohalla (Pre-Chet)',
      nameGurmukhi: 'ਹੋਲਾ ਮਹੱਲਾ',
      nanakshahiDate: '21 Phagan',
      gregorianDate: 'March 4, 2026',
      type: 'festival',
      description: 'Sikh festival of martial arts at Anandpur Sahib (day before Chet Sangrand)',
      year: '1701 CE',
    },
    {
      id: 'mar-14-chet-sangrand',
      name: 'Sangrand - Chet Month Begins (NEW YEAR)',
      nameGurmukhi: 'ਸੰਗਰਾਂਦ - ਚੇਤ (ਨਵਾਂ ਸਾਲ)',
      nanakshahiDate: '1 Chet',
      gregorianDate: 'March 14, 2026',
      type: 'sangrand',
      description: 'Nanakshahi Samvat 558 begins! First month of Sikh calendar',
    },
    {
      id: 'mar-14-masia',
      name: 'Masia (New Moon)',
      nameGurmukhi: 'ਮੱਸਿਆ',
      nanakshahiDate: '1 Chet',
      gregorianDate: 'March 14, 2026',
      type: 'masia',
      description: 'New moon day',
    },
    {
      id: 'mar-14-akali-phula',
      name: 'Shaheedi - Jathedar Akali Phula Singh Ji',
      nameGurmukhi: 'ਅਕਾਲੀ ਫੂਲਾ ਸਿੰਘ ਜੀ ਦੀ ਸ਼ਹੀਦੀ',
      nanakshahiDate: '1 Chet',
      gregorianDate: 'March 14, 2026',
      type: 'martyrdom',
      description: 'Martyrdom of legendary Nihang warrior (201st anniversary)',
      year: '1823 CE',
    },
    {
      id: 'mar-15-baghel-singh',
      name: 'Conquest of Delhi - Sardar Baghel Singh',
      nameGurmukhi: 'ਸਰਦਾਰ ਬਾਗ਼ੇਲ ਸਿੰਘ ਦਾ ਦਿੱਲੀ ਤੇ ਕਬਜ਼ਾ',
      nanakshahiDate: '2 Chet',
      gregorianDate: 'March 15, 2026',
      type: 'historical',
      description: 'Sardar Baghel Singh conquered Delhi and built many Gurdwaras',
      year: '1783 CE',
    },
    {
      id: 'mar-15-hola-mohalla',
      name: 'Hola Mohalla',
      nameGurmukhi: 'ਹੋਲਾ ਮਹੱਲਾ',
      nanakshahiDate: '2 Chet',
      gregorianDate: 'March 15, 2026',
      type: 'festival',
      description: 'Three-day Sikh festival of martial arts, started by Guru Gobind Singh Ji at Anandpur Sahib',
      year: '1701 CE',
    },
    {
      id: 'mar-23-bhagat-singh',
      name: 'Shaheedi - Shaheed Bhagat Singh',
      nameGurmukhi: 'ਸ਼ਹੀਦ ਭਗਤ ਸਿੰਘ',
      nanakshahiDate: '10 Chet',
      gregorianDate: 'March 23, 2026',
      type: 'martyrdom',
      description: 'Martyrdom of freedom fighter Bhagat Singh, Rajguru & Sukhdev',
      year: '1931 CE',
    },
    {
      id: 'mar-25-subheg-shabaz',
      name: 'Shaheedi - Bhai Subheg Singh & Shabaz Singh',
      nameGurmukhi: 'ਭਾਈ ਸੁਭੇਗ ਸਿੰਘ ਤੇ ਸ਼ਬਾਜ਼ ਸਿੰਘ ਦੀ ਸ਼ਹੀਦੀ',
      nanakshahiDate: '12 Chet',
      gregorianDate: 'March 25, 2026',
      type: 'martyrdom',
      description: 'Father-son duo martyred at Red Fort, Delhi',
      year: '1745 CE',
    },
    {
      id: 'mar-27-guru7-gurgaddi',
      name: 'Gurgaddi - Guru Har Rai Ji',
      nameGurmukhi: 'ਗੁਰੂ ਹਰ ਰਾਇ ਜੀ ਦੀ ਗੁਰਗੱਦੀ',
      nanakshahiDate: '14 Chet',
      gregorianDate: 'March 27, 2026',
      type: 'gurgaddi',
      description: 'Guruship bestowed upon Guru Har Rai Ji',
      year: '1644 CE',
    },
    {
      id: 'mar-29-puranmasi',
      name: 'Puranmasi (Full Moon)',
      nameGurmukhi: 'ਪੂਰਨਮਾਸੀ',
      nanakshahiDate: '16 Chet',
      gregorianDate: 'March 29, 2026',
      type: 'puranmasi',
      description: 'Full moon day',
    },
    {
      id: 'mar-30-guru3-gurgaddi',
      name: 'Gurgaddi - Guru Amar Das Ji',
      nameGurmukhi: 'ਗੁਰੂ ਅਮਰ ਦਾਸ ਜੀ ਦੀ ਗੁਰਗੱਦੀ',
      nanakshahiDate: '17 Chet',
      gregorianDate: 'March 30, 2026',
      type: 'gurgaddi',
      description: 'Guruship bestowed upon Guru Amar Das Ji',
      year: '1552 CE',
    },

    // ===== APRIL 2026 =====
    {
      id: 'apr-01-guru2-jotijot',
      name: 'Joti Jot - Guru Angad Dev Ji',
      nameGurmukhi: 'ਗੁਰੂ ਅੰਗਦ ਦੇਵ ਜੀ ਦਾ ਜੋਤੀ ਜੋਤ',
      nanakshahiDate: '19 Chet',
      gregorianDate: 'April 1, 2026',
      type: 'jotijot',
      description: 'Guru Angad Dev Ji merged with eternal light',
      year: '1552 CE',
    },
    {
      id: 'apr-02-guru6-jotijot',
      name: 'Joti Jot - Guru Hargobind Ji',
      nameGurmukhi: 'ਗੁਰੂ ਹਰਗੋਬਿੰਦ ਜੀ ਦਾ ਜੋਤੀ ਜੋਤ',
      nanakshahiDate: '20 Chet',
      gregorianDate: 'April 2, 2026',
      type: 'jotijot',
      description: 'Guru Hargobind Ji merged with eternal light',
      year: '1644 CE',
    },
    {
      id: 'apr-09-jujhar-singh-birth',
      name: 'Birthday - Sahibzada Baba Jujhar Singh Ji',
      nameGurmukhi: 'ਸਾਹਿਬਜ਼ਾਦਾ ਬਾਬਾ ਜੁਝਾਰ ਸਿੰਘ ਜੀ ਦਾ ਜਨਮ',
      nanakshahiDate: '27 Chet',
      gregorianDate: 'April 9, 2026',
      type: 'birth',
      description: 'Birth of second son of Guru Gobind Singh Ji',
      year: '1691 CE',
    },
    {
      id: 'apr-11-guru9-gurgaddi',
      name: 'Gurgaddi - Guru Tegh Bahadur Ji',
      nameGurmukhi: 'ਗੁਰੂ ਤੇਗ ਬਹਾਦਰ ਜੀ ਦੀ ਗੁਰਗੱਦੀ',
      nanakshahiDate: '29 Chet',
      gregorianDate: 'April 11, 2026',
      type: 'gurgaddi',
      description: 'Guruship bestowed upon Guru Tegh Bahadur Ji',
      year: '1664 CE',
    },
    {
      id: 'apr-11-guru8-jotijot',
      name: 'Joti Jot - Guru Har Krishan Ji',
      nameGurmukhi: 'ਗੁਰੂ ਹਰ ਕ੍ਰਿਸ਼ਨ ਜੀ ਦਾ ਜੋਤੀ ਜੋਤ',
      nanakshahiDate: '29 Chet',
      gregorianDate: 'April 11, 2026',
      type: 'jotijot',
      description: 'Guru Har Krishan Ji merged with eternal light (at age 7)',
      year: '1664 CE',
    },
    {
      id: 'apr-12-masia',
      name: 'Masia (New Moon)',
      nameGurmukhi: 'ਮੱਸਿਆ',
      nanakshahiDate: '30 Chet',
      gregorianDate: 'April 12, 2026',
      type: 'masia',
      description: 'New moon day',
    },
    {
      id: 'apr-13-vaisakhi-sangrand',
      name: 'Sangrand - Vaisakh Month Begins',
      nameGurmukhi: 'ਸੰਗਰਾਂਦ - ਵੈਸਾਖ',
      nanakshahiDate: '1 Vaisakh',
      gregorianDate: 'April 13, 2026',
      type: 'sangrand',
      description: 'First day of Vaisakh month',
    },
    {
      id: 'apr-13-khalsa-sajna',
      name: 'Vaisakhi - Khalsa Saajna Divas',
      nameGurmukhi: 'ਵੈਸਾਖੀ - ਖ਼ਾਲਸਾ ਸਾਜਣਾ ਦਿਵਸ',
      nanakshahiDate: '1 Vaisakh',
      gregorianDate: 'April 13, 2026',
      type: 'festival',
      description: 'Birth of Khalsa by Guru Gobind Singh Ji at Anandpur Sahib. Panj Pyare initiated.',
      year: '1699 CE',
    },
    {
      id: 'apr-13-dastar-divas',
      name: 'Sikh Dastar Divas (Turban Day)',
      nameGurmukhi: 'ਸਿੱਖ ਦਸਤਾਰ ਦਿਵਸ',
      nanakshahiDate: '1 Vaisakh',
      gregorianDate: 'April 13, 2026',
      type: 'festival',
      description: 'Celebrating the Sikh turban as symbol of sovereignty and spirituality',
    },
    {
      id: 'apr-18-guru9-parkash',
      name: 'Parkash Purab - Guru Tegh Bahadur Ji',
      nameGurmukhi: 'ਗੁਰੂ ਤੇਗ ਬਹਾਦਰ ਜੀ ਦਾ ਪ੍ਰਕਾਸ਼ ਪੁਰਬ',
      nanakshahiDate: '6 Vaisakh',
      gregorianDate: 'April 18, 2026',
      type: 'gurpurab',
      description: 'Birth of ninth Sikh Guru',
      year: '1621 CE',
    },
    {
      id: 'apr-20-guru5-parkash',
      name: 'Parkash Purab - Guru Arjan Dev Ji',
      nameGurmukhi: 'ਗੁਰੂ ਅਰਜਨ ਦੇਵ ਜੀ ਦਾ ਪ੍ਰਕਾਸ਼ ਪੁਰਬ',
      nanakshahiDate: '8 Vaisakh',
      gregorianDate: 'April 20, 2026',
      type: 'gurpurab',
      description: 'Birth of fifth Sikh Guru, compiler of Adi Granth',
      year: '1563 CE',
    },
    {
      id: 'apr-20-bhagat-dhanna',
      name: 'Birth - Bhagat Dhanna Ji',
      nameGurmukhi: 'ਭਗਤ ਧੰਨਾ ਜੀ ਦਾ ਜਨਮ',
      nanakshahiDate: '8 Vaisakh',
      gregorianDate: 'April 20, 2026',
      type: 'birth',
      description: 'Birth of Bhagat Dhanna Ji, whose hymns are in Guru Granth Sahib',
    },
    {
      id: 'apr-27-puranmasi',
      name: 'Puranmasi (Full Moon)',
      nameGurmukhi: 'ਪੂਰਨਮਾਸੀ',
      nanakshahiDate: '15 Vaisakh',
      gregorianDate: 'April 27, 2026',
      type: 'puranmasi',
      description: 'Full moon day',
    },
    {
      id: 'apr-28-guru2-parkash',
      name: 'Parkash Purab - Guru Angad Dev Ji',
      nameGurmukhi: 'ਗੁਰੂ ਅੰਗਦ ਦੇਵ ਜੀ ਦਾ ਪ੍ਰਕਾਸ਼ ਪੁਰਬ',
      nanakshahiDate: '16 Vaisakh',
      gregorianDate: 'April 28, 2026',
      type: 'gurpurab',
      description: 'Birth of second Sikh Guru who standardized Gurmukhi script',
      year: '1504 CE',
    },

    // Continue with remaining months... (May through December)
    // Due to length, showing structure - you can add all remaining dates

  ];
}
